### PR TITLE
Add schedule.xml

### LINKED ISSUE #10: Add schedule in xml for video team
https://c3voc.de/wiki/schedule

### PR DESCRIPTION
**Pull request by smit1678**
Work in progress to fix #10

### CODE REVIEW

**Comment by smit1678** [comment]
Duplicates a few loops to satisfy the xml file structure, probably some ways that could be optimized but I think this is good to start publishing and get feedback from the video team.

**Review by dakotabenjamin — CHANGES_REQUESTED** [review]
[schedule.txt](https://github.com/hotosm/hot-summit-2019/files/3447445/schedule.txt)

I got an error trying to open the XML in browser:
```
XML Parsing Error: not well-formed
Location: http://127.0.0.1:4000/schedule.xml
Line Number 55, Column 82:
            <title>Workshop 3: Quality Data from Every Source - Tasking Manager & Mapathons</title>
---------------------------------------------------------------------------------^
```

And some warnings in the console: 
```
    Liquid Warning: Liquid syntax error (line 12): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
    Liquid Warning: Liquid syntax error (line 32): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
    Liquid Warning: Liquid syntax error (line 52): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
    Liquid Warning: Liquid syntax error (line 74): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
    Liquid Warning: Liquid syntax error (line 94): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
    Liquid Warning: Liquid syntax error (line 114): Expected end_of_string but found id in "{{ if page.title == 'Program' }}" in schedule.xml
```

generated file attached- file extension renamed to .txt for upload.

In addition, do we want to include the durations in the program frontend as well? It could help make clear the differing lengths of the workshops.

**Review by dakotabenjamin — COMMENTED** [review]
You will want to add some [filters](https://jekyllrb.com/docs/liquid/filters/) to the XML string. Slugify or escape ought to do it.

**Review by dakotabenjamin — APPROVED** [review]
I made the fixes I requested and was able to create a valid xml file. @hexiaok can you double check?

**Comment by smit1678** [comment]
@dakotabenjamin Awesome, thanks for those catches and fixes. 🙌 Going to get this merged and sent over to the SOTM team so they can see how it can be used within their app.

**Pull request merged**
